
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-24T13:08:41-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6bdb55f427e81b58a473c011e1cc930e62ea2c4",
 "version": "2024.12.24.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
