"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import tendermint.types.types_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CanonicalBlockID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HASH_FIELD_NUMBER: builtins.int
    PART_SET_HEADER_FIELD_NUMBER: builtins.int
    hash: builtins.bytes
    @property
    def part_set_header(self) -> global___CanonicalPartSetHeader: ...
    def __init__(
        self,
        *,
        hash: builtins.bytes = ...,
        part_set_header: global___CanonicalPartSetHeader | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["part_set_header", b"part_set_header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["hash", b"hash", "part_set_header", b"part_set_header"]) -> None: ...

global___CanonicalBlockID = CanonicalBlockID

@typing.final
class CanonicalPartSetHeader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOTAL_FIELD_NUMBER: builtins.int
    HASH_FIELD_NUMBER: builtins.int
    total: builtins.int
    hash: builtins.bytes
    def __init__(
        self,
        *,
        total: builtins.int = ...,
        hash: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["hash", b"hash", "total", b"total"]) -> None: ...

global___CanonicalPartSetHeader = CanonicalPartSetHeader

@typing.final
class CanonicalProposal(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    ROUND_FIELD_NUMBER: builtins.int
    POL_ROUND_FIELD_NUMBER: builtins.int
    BLOCK_ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    CHAIN_ID_FIELD_NUMBER: builtins.int
    type: tendermint.types.types_pb2.SignedMsgType.ValueType
    """type alias for byte"""
    height: builtins.int
    """canonicalization requires fixed size encoding here"""
    round: builtins.int
    """canonicalization requires fixed size encoding here"""
    pol_round: builtins.int
    chain_id: builtins.str
    @property
    def block_id(self) -> global___CanonicalBlockID: ...
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        type: tendermint.types.types_pb2.SignedMsgType.ValueType = ...,
        height: builtins.int = ...,
        round: builtins.int = ...,
        pol_round: builtins.int = ...,
        block_id: global___CanonicalBlockID | None = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        chain_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["block_id", b"block_id", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["block_id", b"block_id", "chain_id", b"chain_id", "height", b"height", "pol_round", b"pol_round", "round", b"round", "timestamp", b"timestamp", "type", b"type"]) -> None: ...

global___CanonicalProposal = CanonicalProposal

@typing.final
class CanonicalVote(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    ROUND_FIELD_NUMBER: builtins.int
    BLOCK_ID_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    CHAIN_ID_FIELD_NUMBER: builtins.int
    type: tendermint.types.types_pb2.SignedMsgType.ValueType
    """type alias for byte"""
    height: builtins.int
    """canonicalization requires fixed size encoding here"""
    round: builtins.int
    """canonicalization requires fixed size encoding here"""
    chain_id: builtins.str
    @property
    def block_id(self) -> global___CanonicalBlockID: ...
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        type: tendermint.types.types_pb2.SignedMsgType.ValueType = ...,
        height: builtins.int = ...,
        round: builtins.int = ...,
        block_id: global___CanonicalBlockID | None = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        chain_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["block_id", b"block_id", "timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["block_id", b"block_id", "chain_id", b"chain_id", "height", b"height", "round", b"round", "timestamp", b"timestamp", "type", b"type"]) -> None: ...

global___CanonicalVote = CanonicalVote

@typing.final
class CanonicalVoteExtension(google.protobuf.message.Message):
    """CanonicalVoteExtension provides us a way to serialize a vote extension from
    a particular validator such that we can sign over those serialized bytes.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXTENSION_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    ROUND_FIELD_NUMBER: builtins.int
    CHAIN_ID_FIELD_NUMBER: builtins.int
    extension: builtins.bytes
    height: builtins.int
    round: builtins.int
    chain_id: builtins.str
    def __init__(
        self,
        *,
        extension: builtins.bytes = ...,
        height: builtins.int = ...,
        round: builtins.int = ...,
        chain_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chain_id", b"chain_id", "extension", b"extension", "height", b"height", "round", b"round"]) -> None: ...

global___CanonicalVoteExtension = CanonicalVoteExtension
