# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import facerec_pb2 as facerec__pb2


class FaceRecStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFaces = channel.unary_unary(
                '/facerec.FaceRec/GetFaces',
                request_serializer=facerec__pb2.ImageReq.SerializeToString,
                response_deserializer=facerec__pb2.FaceResp.FromString,
                )
        self.GetFeatures = channel.unary_unary(
                '/facerec.FaceRec/GetFeatures',
                request_serializer=facerec__pb2.ImageReq.SerializeToString,
                response_deserializer=facerec__pb2.FeatureResp.FromString,
                )


class FaceRecServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFaces(self, request, context):
        """获取识别人脸(rect)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeatures(self, request, context):
        """获取人脸特征
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceRecServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFaces,
                    request_deserializer=facerec__pb2.ImageReq.FromString,
                    response_serializer=facerec__pb2.FaceResp.SerializeToString,
            ),
            'GetFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeatures,
                    request_deserializer=facerec__pb2.ImageReq.FromString,
                    response_serializer=facerec__pb2.FeatureResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'facerec.FaceRec', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceRec(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/facerec.FaceRec/GetFaces',
            facerec__pb2.ImageReq.SerializeToString,
            facerec__pb2.FaceResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/facerec.FaceRec/GetFeatures',
            facerec__pb2.ImageReq.SerializeToString,
            facerec__pb2.FeatureResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
