#!/usr/bin/env python3
# THIS "versionfile" IS GENERATED BY version-pioneer-0.0.9
# by evaluating the original versionscript and storing the computed versions as a constant.

def get_version_dict():
    return {'version': '0.0.9', 'full_revisionid': '1d83ffdf90ff218966f63080339b9ae193937b75', 'dirty': False, 'error': None, 'date': '2024-12-27T08:54:37+0000'}


if __name__ == "__main__":
    import json

    print(json.dumps(get_version_dict()))