"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import tendermint.crypto.keys_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PacketPing(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PacketPing = PacketPing

@typing.final
class PacketPong(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___PacketPong = PacketPong

@typing.final
class PacketMsg(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CHANNEL_ID_FIELD_NUMBER: builtins.int
    EOF_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    channel_id: builtins.int
    eof: builtins.bool
    data: builtins.bytes
    def __init__(
        self,
        *,
        channel_id: builtins.int = ...,
        eof: builtins.bool = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["channel_id", b"channel_id", "data", b"data", "eof", b"eof"]) -> None: ...

global___PacketMsg = PacketMsg

@typing.final
class Packet(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PACKET_PING_FIELD_NUMBER: builtins.int
    PACKET_PONG_FIELD_NUMBER: builtins.int
    PACKET_MSG_FIELD_NUMBER: builtins.int
    @property
    def packet_ping(self) -> global___PacketPing: ...
    @property
    def packet_pong(self) -> global___PacketPong: ...
    @property
    def packet_msg(self) -> global___PacketMsg: ...
    def __init__(
        self,
        *,
        packet_ping: global___PacketPing | None = ...,
        packet_pong: global___PacketPong | None = ...,
        packet_msg: global___PacketMsg | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["packet_msg", b"packet_msg", "packet_ping", b"packet_ping", "packet_pong", b"packet_pong", "sum", b"sum"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["packet_msg", b"packet_msg", "packet_ping", b"packet_ping", "packet_pong", b"packet_pong", "sum", b"sum"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["sum", b"sum"]) -> typing.Literal["packet_ping", "packet_pong", "packet_msg"] | None: ...

global___Packet = Packet

@typing.final
class AuthSigMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUB_KEY_FIELD_NUMBER: builtins.int
    SIG_FIELD_NUMBER: builtins.int
    sig: builtins.bytes
    @property
    def pub_key(self) -> tendermint.crypto.keys_pb2.PublicKey: ...
    def __init__(
        self,
        *,
        pub_key: tendermint.crypto.keys_pb2.PublicKey | None = ...,
        sig: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pub_key", b"pub_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["pub_key", b"pub_key", "sig", b"sig"]) -> None: ...

global___AuthSigMessage = AuthSigMessage
