"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .createwebhookresponse import CreateWebhookResponse, CreateWebhookResponseTypedDict
from .unexpectederrorresponse import (
    UnexpectedErrorResponse,
    UnexpectedErrorResponseTypedDict,
)
from apideck_unify.types import BaseModel
from apideck_unify.utils import FieldMetadata, HeaderMetadata
import pydantic
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class WebhookWebhooksAddGlobalsTypedDict(TypedDict):
    app_id: NotRequired[str]
    r"""The ID of your Unify application"""


class WebhookWebhooksAddGlobals(BaseModel):
    app_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-app-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The ID of your Unify application"""


WebhookWebhooksAddResponseTypedDict = TypeAliasType(
    "WebhookWebhooksAddResponseTypedDict",
    Union[CreateWebhookResponseTypedDict, UnexpectedErrorResponseTypedDict],
)


WebhookWebhooksAddResponse = TypeAliasType(
    "WebhookWebhooksAddResponse", Union[CreateWebhookResponse, UnexpectedErrorResponse]
)
