from typing import Literal

HFModelType = Literal[
    "huggingface:Qwen/Qwen2.5-72B-Instruct",
    "huggingface:Qwen/QwQ-32B-Preview",
    "huggingface:Qwen/Qwen2.5-Coder-32B-Instruct",
    "huggingface:NousResearch/Hermes-3-Llama-3.1-8B",
    "huggingface:microsoft/Phi-3.5-mini-instruct",
    "huggingface:meta-llama/Llama-3.1-8B-Instruct",
    "huggingface:meta-llama/Llama-3.2-1B-Instruct",
    "huggingface:meta-llama/Llama-3.2-3B-Instruct",
    "huggingface:01-ai/Yi-1.5-34B-Chat",
    "huggingface:codellama/CodeLlama-34b-Instruct-hf",
    "huggingface:google/gemma-1.1-7b-it",
    "huggingface:google/gemma-2-2b-it",
    "huggingface:google/gemma-2-9b-it",
    "huggingface:google/gemma-2b-it",
    "huggingface:HuggingFaceH4/starchat2-15b-v0.1",
    "huggingface:HuggingFaceH4/zephyr-7b-alpha",
    "huggingface:HuggingFaceH4/zephyr-7b-beta",
    "huggingface:meta-llama/Llama-2-7b-chat-hf",
    "huggingface:meta-llama/Llama-3.1-70B-Instruct",
    "huggingface:meta-llama/Meta-Llama-3-70B-Instruct",
    "huggingface:meta-llama/Meta-Llama-3-8B-Instruct",
    "huggingface:microsoft/DialoGPT-medium",
    "huggingface:microsoft/Phi-3-mini-4k-instruct",
    "huggingface:mistralai/Mistral-7B-Instruct-v0.2",
    "huggingface:mistralai/Mistral-7B-Instruct-v0.3",
    "huggingface:mistralai/Mixtral-8x7B-Instruct-v0.1",
    "huggingface:NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO",
    "huggingface:Qwen/Qwen2.5-1.5B-Instruct",
    "huggingface:Qwen/Qwen2.5-3B-Instruct",
    "huggingface:tiiuae/falcon-7b-instruct",
    "huggingface:uschreiber/llama3.2"
]