"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import tendermint.abci.types_pb2
import tendermint.types.params_pb2
import tendermint.types.types_pb2
import tendermint.types.validator_pb2
import tendermint.version.types_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class LegacyABCIResponses(google.protobuf.message.Message):
    """LegacyABCIResponses retains the responses
    of the legacy ABCI calls during block processing.
    Note ReponseDeliverTx is renamed to ExecTxResult but they are semantically the same
    Kept for backwards compatibility for versions prior to v0.38
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DELIVER_TXS_FIELD_NUMBER: builtins.int
    END_BLOCK_FIELD_NUMBER: builtins.int
    BEGIN_BLOCK_FIELD_NUMBER: builtins.int
    @property
    def deliver_txs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[tendermint.abci.types_pb2.ExecTxResult]: ...
    @property
    def end_block(self) -> global___ResponseEndBlock: ...
    @property
    def begin_block(self) -> global___ResponseBeginBlock: ...
    def __init__(
        self,
        *,
        deliver_txs: collections.abc.Iterable[tendermint.abci.types_pb2.ExecTxResult] | None = ...,
        end_block: global___ResponseEndBlock | None = ...,
        begin_block: global___ResponseBeginBlock | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["begin_block", b"begin_block", "end_block", b"end_block"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["begin_block", b"begin_block", "deliver_txs", b"deliver_txs", "end_block", b"end_block"]) -> None: ...

global___LegacyABCIResponses = LegacyABCIResponses

@typing.final
class ResponseBeginBlock(google.protobuf.message.Message):
    """ResponseBeginBlock is kept for backwards compatibility for versions prior to v0.38"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENTS_FIELD_NUMBER: builtins.int
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[tendermint.abci.types_pb2.Event]: ...
    def __init__(
        self,
        *,
        events: collections.abc.Iterable[tendermint.abci.types_pb2.Event] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["events", b"events"]) -> None: ...

global___ResponseBeginBlock = ResponseBeginBlock

@typing.final
class ResponseEndBlock(google.protobuf.message.Message):
    """ResponseEndBlock is kept for backwards compatibility for versions prior to v0.38"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALIDATOR_UPDATES_FIELD_NUMBER: builtins.int
    CONSENSUS_PARAM_UPDATES_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    @property
    def validator_updates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[tendermint.abci.types_pb2.ValidatorUpdate]: ...
    @property
    def consensus_param_updates(self) -> tendermint.types.params_pb2.ConsensusParams: ...
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[tendermint.abci.types_pb2.Event]: ...
    def __init__(
        self,
        *,
        validator_updates: collections.abc.Iterable[tendermint.abci.types_pb2.ValidatorUpdate] | None = ...,
        consensus_param_updates: tendermint.types.params_pb2.ConsensusParams | None = ...,
        events: collections.abc.Iterable[tendermint.abci.types_pb2.Event] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["consensus_param_updates", b"consensus_param_updates"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["consensus_param_updates", b"consensus_param_updates", "events", b"events", "validator_updates", b"validator_updates"]) -> None: ...

global___ResponseEndBlock = ResponseEndBlock

@typing.final
class ValidatorsInfo(google.protobuf.message.Message):
    """ValidatorsInfo represents the latest validator set, or the last height it changed"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALIDATOR_SET_FIELD_NUMBER: builtins.int
    LAST_HEIGHT_CHANGED_FIELD_NUMBER: builtins.int
    last_height_changed: builtins.int
    @property
    def validator_set(self) -> tendermint.types.validator_pb2.ValidatorSet: ...
    def __init__(
        self,
        *,
        validator_set: tendermint.types.validator_pb2.ValidatorSet | None = ...,
        last_height_changed: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["validator_set", b"validator_set"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["last_height_changed", b"last_height_changed", "validator_set", b"validator_set"]) -> None: ...

global___ValidatorsInfo = ValidatorsInfo

@typing.final
class ConsensusParamsInfo(google.protobuf.message.Message):
    """ConsensusParamsInfo represents the latest consensus params, or the last height it changed"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONSENSUS_PARAMS_FIELD_NUMBER: builtins.int
    LAST_HEIGHT_CHANGED_FIELD_NUMBER: builtins.int
    last_height_changed: builtins.int
    @property
    def consensus_params(self) -> tendermint.types.params_pb2.ConsensusParams: ...
    def __init__(
        self,
        *,
        consensus_params: tendermint.types.params_pb2.ConsensusParams | None = ...,
        last_height_changed: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["consensus_params", b"consensus_params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["consensus_params", b"consensus_params", "last_height_changed", b"last_height_changed"]) -> None: ...

global___ConsensusParamsInfo = ConsensusParamsInfo

@typing.final
class ABCIResponsesInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LEGACY_ABCI_RESPONSES_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    RESPONSE_FINALIZE_BLOCK_FIELD_NUMBER: builtins.int
    height: builtins.int
    @property
    def legacy_abci_responses(self) -> global___LegacyABCIResponses: ...
    @property
    def response_finalize_block(self) -> tendermint.abci.types_pb2.ResponseFinalizeBlock: ...
    def __init__(
        self,
        *,
        legacy_abci_responses: global___LegacyABCIResponses | None = ...,
        height: builtins.int = ...,
        response_finalize_block: tendermint.abci.types_pb2.ResponseFinalizeBlock | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["legacy_abci_responses", b"legacy_abci_responses", "response_finalize_block", b"response_finalize_block"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["height", b"height", "legacy_abci_responses", b"legacy_abci_responses", "response_finalize_block", b"response_finalize_block"]) -> None: ...

global___ABCIResponsesInfo = ABCIResponsesInfo

@typing.final
class Version(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONSENSUS_FIELD_NUMBER: builtins.int
    SOFTWARE_FIELD_NUMBER: builtins.int
    software: builtins.str
    @property
    def consensus(self) -> tendermint.version.types_pb2.Consensus: ...
    def __init__(
        self,
        *,
        consensus: tendermint.version.types_pb2.Consensus | None = ...,
        software: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["consensus", b"consensus"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["consensus", b"consensus", "software", b"software"]) -> None: ...

global___Version = Version

@typing.final
class State(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    CHAIN_ID_FIELD_NUMBER: builtins.int
    INITIAL_HEIGHT_FIELD_NUMBER: builtins.int
    LAST_BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    LAST_BLOCK_ID_FIELD_NUMBER: builtins.int
    LAST_BLOCK_TIME_FIELD_NUMBER: builtins.int
    NEXT_VALIDATORS_FIELD_NUMBER: builtins.int
    VALIDATORS_FIELD_NUMBER: builtins.int
    LAST_VALIDATORS_FIELD_NUMBER: builtins.int
    LAST_HEIGHT_VALIDATORS_CHANGED_FIELD_NUMBER: builtins.int
    CONSENSUS_PARAMS_FIELD_NUMBER: builtins.int
    LAST_HEIGHT_CONSENSUS_PARAMS_CHANGED_FIELD_NUMBER: builtins.int
    LAST_RESULTS_HASH_FIELD_NUMBER: builtins.int
    APP_HASH_FIELD_NUMBER: builtins.int
    chain_id: builtins.str
    """immutable"""
    initial_height: builtins.int
    last_block_height: builtins.int
    """LastBlockHeight=0 at genesis (ie. block(H=0) does not exist)"""
    last_height_validators_changed: builtins.int
    last_height_consensus_params_changed: builtins.int
    last_results_hash: builtins.bytes
    """Merkle root of the results from executing prev block"""
    app_hash: builtins.bytes
    """the latest AppHash we've received from calling abci.Commit()"""
    @property
    def version(self) -> global___Version: ...
    @property
    def last_block_id(self) -> tendermint.types.types_pb2.BlockID: ...
    @property
    def last_block_time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def next_validators(self) -> tendermint.types.validator_pb2.ValidatorSet:
        """LastValidators is used to validate block.LastCommit.
        Validators are persisted to the database separately every time they change,
        so we can query for historical validator sets.
        Note that if s.LastBlockHeight causes a valset change,
        we set s.LastHeightValidatorsChanged = s.LastBlockHeight + 1 + 1
        Extra +1 due to nextValSet delay.
        """

    @property
    def validators(self) -> tendermint.types.validator_pb2.ValidatorSet: ...
    @property
    def last_validators(self) -> tendermint.types.validator_pb2.ValidatorSet: ...
    @property
    def consensus_params(self) -> tendermint.types.params_pb2.ConsensusParams:
        """Consensus parameters used for validating blocks.
        Changes returned by EndBlock and updated after Commit.
        """

    def __init__(
        self,
        *,
        version: global___Version | None = ...,
        chain_id: builtins.str = ...,
        initial_height: builtins.int = ...,
        last_block_height: builtins.int = ...,
        last_block_id: tendermint.types.types_pb2.BlockID | None = ...,
        last_block_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        next_validators: tendermint.types.validator_pb2.ValidatorSet | None = ...,
        validators: tendermint.types.validator_pb2.ValidatorSet | None = ...,
        last_validators: tendermint.types.validator_pb2.ValidatorSet | None = ...,
        last_height_validators_changed: builtins.int = ...,
        consensus_params: tendermint.types.params_pb2.ConsensusParams | None = ...,
        last_height_consensus_params_changed: builtins.int = ...,
        last_results_hash: builtins.bytes = ...,
        app_hash: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["consensus_params", b"consensus_params", "last_block_id", b"last_block_id", "last_block_time", b"last_block_time", "last_validators", b"last_validators", "next_validators", b"next_validators", "validators", b"validators", "version", b"version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["app_hash", b"app_hash", "chain_id", b"chain_id", "consensus_params", b"consensus_params", "initial_height", b"initial_height", "last_block_height", b"last_block_height", "last_block_id", b"last_block_id", "last_block_time", b"last_block_time", "last_height_consensus_params_changed", b"last_height_consensus_params_changed", "last_height_validators_changed", b"last_height_validators_changed", "last_results_hash", b"last_results_hash", "last_validators", b"last_validators", "next_validators", b"next_validators", "validators", b"validators", "version", b"version"]) -> None: ...

global___State = State
