# Generated by ariadne-codegen
# Source: combined.graphql

from typing import Any

from .base_model import BaseModel


class CreateBindingSiteConformer(BaseModel):
    create_binding_site_conformer: "CreateBindingSiteConformerCreateBindingSiteConformer"


class CreateBindingSiteConformerCreateBindingSiteConformer(BaseModel):
    id: Any


CreateBindingSiteConformer.model_rebuild()
