from pathlib import Path

DATA_OUTPUT_FILE = "data.txt"
LOG_OUTPUT_FILE = "log.txt"
PID_FILE_NAME = "pid.txt"
QUEUE_PID_FILE = "qid.txt"
BASE_PATH = Path.home()
PID_FILE_LOCATION = BASE_PATH / ".orkestr8" / PID_FILE_NAME
DATA_OUTPUT_FILE_LOCATION = BASE_PATH / DATA_OUTPUT_FILE
QUEUE_PID_FILE_LOCATION = BASE_PATH / ".orkestr8" / QUEUE_PID_FILE
LOG_OUTPUT_FILE_LOCATION = BASE_PATH / ".orkestr8" / "service.log"
