
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-26T21:20:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4bd8dd9c734c4990c2390025343ae312ff8327a",
 "version": "1.89.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
