# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: org/polypheny/prism/connection_responses.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.org/polypheny/prism/connection_responses.proto\x12\x13org.polypheny.prism\"a\n\x12\x43onnectionResponse\x12\x15\n\ris_compatible\x18\x01 \x01(\x08\x12\x19\n\x11major_api_version\x18\x02 \x01(\x05\x12\x19\n\x11minor_api_version\x18\x03 \x01(\x05\"\x14\n\x12\x44isconnectResponse\"\x19\n\x17\x43onnectionCheckResponse\"$\n\"ConnectionPropertiesUpdateResponseBY\n\x13org.polypheny.prismB\x13\x43onnectionResponsesP\x01Z\x19org/polypheny/prism;prism\xaa\x02\x0fPolypheny.Prismb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'org.polypheny.prism.connection_responses_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023org.polypheny.prismB\023ConnectionResponsesP\001Z\031org/polypheny/prism;prism\252\002\017Polypheny.Prism'
  _globals['_CONNECTIONRESPONSE']._serialized_start=71
  _globals['_CONNECTIONRESPONSE']._serialized_end=168
  _globals['_DISCONNECTRESPONSE']._serialized_start=170
  _globals['_DISCONNECTRESPONSE']._serialized_end=190
  _globals['_CONNECTIONCHECKRESPONSE']._serialized_start=192
  _globals['_CONNECTIONCHECKRESPONSE']._serialized_end=217
  _globals['_CONNECTIONPROPERTIESUPDATERESPONSE']._serialized_start=219
  _globals['_CONNECTIONPROPERTIESUPDATERESPONSE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
