PROJECT_COMMAND_FILE: str = "command.yaml"
PROJECT_DETAILS_FILE: str = "project.yaml"
ARCHITECTURE_DETAILS_FILE: str = "architecture.yaml"
REMOTE_URL_RAW: str = "https://raw.githubusercontent.com/fonipts/pluton-lobby/main/blueprint"
#REMOTE_URL_RAW: str = "https://raw.githubusercontent.com/fonipts/pluton-lobby/refs/heads/dev/1.0.31a1/blueprint"
