# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .additional_source_info import AdditionalSourceInfo
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class SourceInfo(UniversalBaseModel):
    """
    "SourceInfo DTO class.
    """

    name_source: typing.Optional[str] = None
    domain_url: str
    logo: typing.Optional[str] = None
    additional_info: typing.Optional[AdditionalSourceInfo] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
