# Generated by ariadne-codegen
# Source: combined.graphql

from datetime import datetime
from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import BindingSiteInteractionKind, PiStackKind
from .fragments import PageInfoFull


class BindingSiteInteractions(BaseModel):
    me: "BindingSiteInteractionsMe"


class BindingSiteInteractionsMe(BaseModel):
    account: "BindingSiteInteractionsMeAccount"


class BindingSiteInteractionsMeAccount(BaseModel):
    project: "BindingSiteInteractionsMeAccountProject"


class BindingSiteInteractionsMeAccountProject(BaseModel):
    binding_site_interactions: "BindingSiteInteractionsMeAccountProjectBindingSiteInteractions"


class BindingSiteInteractionsMeAccountProjectBindingSiteInteractions(BaseModel):
    page_info: "BindingSiteInteractionsMeAccountProjectBindingSiteInteractionsPageInfo" = Field(
        alias="pageInfo"
    )
    edges: List["BindingSiteInteractionsMeAccountProjectBindingSiteInteractionsEdges"]
    total_count: int


class BindingSiteInteractionsMeAccountProjectBindingSiteInteractionsPageInfo(
    PageInfoFull
):
    pass


class BindingSiteInteractionsMeAccountProjectBindingSiteInteractionsEdges(BaseModel):
    cursor: str
    node: "BindingSiteInteractionsMeAccountProjectBindingSiteInteractionsEdgesNode"


class BindingSiteInteractionsMeAccountProjectBindingSiteInteractionsEdgesNode(
    BaseModel
):
    id: Any
    residues: List[int]
    interactions: List[
        "BindingSiteInteractionsMeAccountProjectBindingSiteInteractionsEdgesNodeInteractions"
    ]
    created_at: datetime
    updated_at: datetime
    deleted_at: Optional[datetime]
    name: Optional[str]
    description: Optional[str]
    run_id: Optional[Any]
    tags: Optional[List[str]]


class BindingSiteInteractionsMeAccountProjectBindingSiteInteractionsEdgesNodeInteractions(
    BaseModel
):
    kind: BindingSiteInteractionKind
    pi_stack_kind: Optional[PiStackKind]
    ligand_atom: Any
    receptor_atom: Any


BindingSiteInteractions.model_rebuild()
BindingSiteInteractionsMe.model_rebuild()
BindingSiteInteractionsMeAccount.model_rebuild()
BindingSiteInteractionsMeAccountProject.model_rebuild()
BindingSiteInteractionsMeAccountProjectBindingSiteInteractions.model_rebuild()
BindingSiteInteractionsMeAccountProjectBindingSiteInteractionsEdges.model_rebuild()
BindingSiteInteractionsMeAccountProjectBindingSiteInteractionsEdgesNode.model_rebuild()
