# Generated by ariadne-codegen
# Source: combined.graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class CreateBindingPoseConformer(BaseModel):
    create_binding_pose_conformer: "CreateBindingPoseConformerCreateBindingPoseConformer"


class CreateBindingPoseConformerCreateBindingPoseConformer(BaseModel):
    id: Any
    name: Optional[str]
    description: Optional[str]
    tags: Optional[List[str]]


CreateBindingPoseConformer.model_rebuild()
