# Generated by ariadne-codegen
# Source: combined.graphql

from typing import Any

from .base_model import BaseModel


class CreateBindingAffinity(BaseModel):
    create_binding_affinity: "CreateBindingAffinityCreateBindingAffinity"


class CreateBindingAffinityCreateBindingAffinity(BaseModel):
    id: Any


CreateBindingAffinity.model_rebuild()
