# Generated by ariadne-codegen
# Source: combined.graphql

from datetime import datetime
from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import PageInfoFull


class ProteinConformers(BaseModel):
    me: "ProteinConformersMe"


class ProteinConformersMe(BaseModel):
    account: "ProteinConformersMeAccount"


class ProteinConformersMeAccount(BaseModel):
    project: "ProteinConformersMeAccountProject"


class ProteinConformersMeAccountProject(BaseModel):
    protein_conformers: "ProteinConformersMeAccountProjectProteinConformers"


class ProteinConformersMeAccountProjectProteinConformers(BaseModel):
    page_info: "ProteinConformersMeAccountProjectProteinConformersPageInfo" = Field(
        alias="pageInfo"
    )
    edges: List["ProteinConformersMeAccountProjectProteinConformersEdges"]
    total_count: int


class ProteinConformersMeAccountProjectProteinConformersPageInfo(PageInfoFull):
    pass


class ProteinConformersMeAccountProjectProteinConformersEdges(BaseModel):
    cursor: str
    node: "ProteinConformersMeAccountProjectProteinConformersEdgesNode"


class ProteinConformersMeAccountProjectProteinConformersEdgesNode(BaseModel):
    id: Any
    residues: List[int]
    created_at: datetime
    updated_at: datetime
    deleted_at: Optional[datetime]
    name: Optional[str]
    description: Optional[str]
    run_id: Optional[Any]
    tags: Optional[List[str]]
    structure: "ProteinConformersMeAccountProjectProteinConformersEdgesNodeStructure"
    protein: "ProteinConformersMeAccountProjectProteinConformersEdgesNodeProtein"


class ProteinConformersMeAccountProjectProteinConformersEdgesNodeStructure(BaseModel):
    id: Any
    rcsb_id: Optional[str]


class ProteinConformersMeAccountProjectProteinConformersEdgesNodeProtein(BaseModel):
    id: Any
    sequence: str


ProteinConformers.model_rebuild()
ProteinConformersMe.model_rebuild()
ProteinConformersMeAccount.model_rebuild()
ProteinConformersMeAccountProject.model_rebuild()
ProteinConformersMeAccountProjectProteinConformers.model_rebuild()
ProteinConformersMeAccountProjectProteinConformersEdges.model_rebuild()
ProteinConformersMeAccountProjectProteinConformersEdgesNode.model_rebuild()
