
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-25T23:30:17+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "55aafbb9c24f18d16f2827978b0bc898fbd25487",
 "version": "0.8.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
