"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .inputtype import InputType
from .vectormodel import VectorModel
from mixpeek.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class EmbeddingRequestTypedDict(TypedDict):
    type: InputType
    embedding_model: VectorModel
    value: NotRequired[Nullable[str]]
    r"""The input content to embed. Could be a URL, text content, file path, or base64 encoded string"""
    field_name: NotRequired[Nullable[str]]
    r"""Field name to insert into the database, if not provided, the embedding will be inserted into the default field"""


class EmbeddingRequest(BaseModel):
    type: InputType

    embedding_model: VectorModel

    value: OptionalNullable[str] = UNSET
    r"""The input content to embed. Could be a URL, text content, file path, or base64 encoded string"""

    field_name: OptionalNullable[str] = UNSET
    r"""Field name to insert into the database, if not provided, the embedding will be inserted into the default field"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["value", "field_name"]
        nullable_fields = ["value", "field_name"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
