# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: poktroll/shared/params.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'poktroll/shared/params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from poktroll_clients.proto.amino import amino_pb2 as amino_dot_amino__pb2
from poktroll_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cpoktroll/shared/params.proto\x12\x0fpoktroll.shared\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\"\xab\x08\n\x06Params\x12O\n\x16num_blocks_per_session\x18\x01 \x01(\x04\x42\x1a\xea\xde\x1f\x16num_blocks_per_sessionR\x13numBlocksPerSession\x12\x66\n\x1egrace_period_end_offset_blocks\x18\x02 \x01(\x04\x42\"\xea\xde\x1f\x1egrace_period_end_offset_blocksR\x1agracePeriodEndOffsetBlocks\x12i\n\x1f\x63laim_window_open_offset_blocks\x18\x03 \x01(\x04\x42#\xea\xde\x1f\x1f\x63laim_window_open_offset_blocksR\x1b\x63laimWindowOpenOffsetBlocks\x12l\n claim_window_close_offset_blocks\x18\x04 \x01(\x04\x42$\xea\xde\x1f claim_window_close_offset_blocksR\x1c\x63laimWindowCloseOffsetBlocks\x12i\n\x1fproof_window_open_offset_blocks\x18\x05 \x01(\x04\x42#\xea\xde\x1f\x1fproof_window_open_offset_blocksR\x1bproofWindowOpenOffsetBlocks\x12l\n proof_window_close_offset_blocks\x18\x06 \x01(\x04\x42$\xea\xde\x1f proof_window_close_offset_blocksR\x1cproofWindowCloseOffsetBlocks\x12s\n\"supplier_unbonding_period_sessions\x18\x07 \x01(\x04\x42&\xea\xde\x1f\"supplier_unbonding_period_sessionsR\x1fsupplierUnbondingPeriodSessions\x12|\n%application_unbonding_period_sessions\x18\x08 \x01(\x04\x42)\xea\xde\x1f%application_unbonding_period_sessionsR\"applicationUnbondingPeriodSessions\x12\x9f\x01\n\"compute_units_to_tokens_multiplier\x18\t \x01(\x04\x42S\xea\xde\x1f\"compute_units_to_tokens_multiplier\xf2\xde\x1f)yaml:\"compute_units_to_tokens_multiplier\"R\x1e\x63omputeUnitsToTokensMultiplier:!\xe8\xa0\x1f\x01\x8a\xe7\xb0*\x18poktroll/x/shared/ParamsB5Z/github.com/pokt-network/poktroll/x/shared/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'poktroll.shared.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/pokt-network/poktroll/x/shared/types\330\342\036\001'
  _globals['_PARAMS'].fields_by_name['num_blocks_per_session']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['num_blocks_per_session']._serialized_options = b'\352\336\037\026num_blocks_per_session'
  _globals['_PARAMS'].fields_by_name['grace_period_end_offset_blocks']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['grace_period_end_offset_blocks']._serialized_options = b'\352\336\037\036grace_period_end_offset_blocks'
  _globals['_PARAMS'].fields_by_name['claim_window_open_offset_blocks']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['claim_window_open_offset_blocks']._serialized_options = b'\352\336\037\037claim_window_open_offset_blocks'
  _globals['_PARAMS'].fields_by_name['claim_window_close_offset_blocks']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['claim_window_close_offset_blocks']._serialized_options = b'\352\336\037 claim_window_close_offset_blocks'
  _globals['_PARAMS'].fields_by_name['proof_window_open_offset_blocks']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['proof_window_open_offset_blocks']._serialized_options = b'\352\336\037\037proof_window_open_offset_blocks'
  _globals['_PARAMS'].fields_by_name['proof_window_close_offset_blocks']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['proof_window_close_offset_blocks']._serialized_options = b'\352\336\037 proof_window_close_offset_blocks'
  _globals['_PARAMS'].fields_by_name['supplier_unbonding_period_sessions']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['supplier_unbonding_period_sessions']._serialized_options = b'\352\336\037\"supplier_unbonding_period_sessions'
  _globals['_PARAMS'].fields_by_name['application_unbonding_period_sessions']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['application_unbonding_period_sessions']._serialized_options = b'\352\336\037%application_unbonding_period_sessions'
  _globals['_PARAMS'].fields_by_name['compute_units_to_tokens_multiplier']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['compute_units_to_tokens_multiplier']._serialized_options = b'\352\336\037\"compute_units_to_tokens_multiplier\362\336\037)yaml:\"compute_units_to_tokens_multiplier\"'
  _globals['_PARAMS']._loaded_options = None
  _globals['_PARAMS']._serialized_options = b'\350\240\037\001\212\347\260*\030poktroll/x/shared/Params'
  _globals['_PARAMS']._serialized_start=91
  _globals['_PARAMS']._serialized_end=1158
# @@protoc_insertion_point(module_scope)
