# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from foreverbull.pb.foreverbull.backtest import engine_service_pb2 as foreverbull_dot_backtest_dot_engine__service__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in foreverbull/backtest/engine_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DownloadIngestion = channel.unary_unary(
                '/foreverbull.backtest.Engine/DownloadIngestion',
                request_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.DownloadIngestionRequest.SerializeToString,
                response_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.DownloadIngestionResponse.FromString,
                _registered_method=True)
        self.Ingest = channel.unary_unary(
                '/foreverbull.backtest.Engine/Ingest',
                request_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.IngestRequest.SerializeToString,
                response_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.RunBacktest = channel.unary_unary(
                '/foreverbull.backtest.Engine/RunBacktest',
                request_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.RunRequest.SerializeToString,
                response_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.RunResponse.FromString,
                _registered_method=True)
        self.GetCurrentPeriod = channel.unary_unary(
                '/foreverbull.backtest.Engine/GetCurrentPeriod',
                request_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.GetCurrentPeriodRequest.SerializeToString,
                response_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.GetCurrentPeriodResponse.FromString,
                _registered_method=True)
        self.PlaceOrdersAndContinue = channel.unary_unary(
                '/foreverbull.backtest.Engine/PlaceOrdersAndContinue',
                request_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.PlaceOrdersAndContinueRequest.SerializeToString,
                response_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.PlaceOrdersAndContinueResponse.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/foreverbull.backtest.Engine/GetResult',
                request_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.GetResultRequest.SerializeToString,
                response_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.GetResultResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/foreverbull.backtest.Engine/Stop',
                request_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.StopRequest.SerializeToString,
                response_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.StopResponse.FromString,
                _registered_method=True)


class EngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DownloadIngestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ingest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentPeriod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrdersAndContinue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DownloadIngestion': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadIngestion,
                    request_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.DownloadIngestionRequest.FromString,
                    response_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.DownloadIngestionResponse.SerializeToString,
            ),
            'Ingest': grpc.unary_unary_rpc_method_handler(
                    servicer.Ingest,
                    request_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.IngestRequest.FromString,
                    response_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.IngestResponse.SerializeToString,
            ),
            'RunBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.RunBacktest,
                    request_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.RunRequest.FromString,
                    response_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.RunResponse.SerializeToString,
            ),
            'GetCurrentPeriod': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentPeriod,
                    request_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.GetCurrentPeriodRequest.FromString,
                    response_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.GetCurrentPeriodResponse.SerializeToString,
            ),
            'PlaceOrdersAndContinue': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrdersAndContinue,
                    request_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.PlaceOrdersAndContinueRequest.FromString,
                    response_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.PlaceOrdersAndContinueResponse.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.GetResultRequest.FromString,
                    response_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.GetResultResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=foreverbull_dot_backtest_dot_engine__service__pb2.StopRequest.FromString,
                    response_serializer=foreverbull_dot_backtest_dot_engine__service__pb2.StopResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'foreverbull.backtest.Engine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('foreverbull.backtest.Engine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Engine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DownloadIngestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foreverbull.backtest.Engine/DownloadIngestion',
            foreverbull_dot_backtest_dot_engine__service__pb2.DownloadIngestionRequest.SerializeToString,
            foreverbull_dot_backtest_dot_engine__service__pb2.DownloadIngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ingest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foreverbull.backtest.Engine/Ingest',
            foreverbull_dot_backtest_dot_engine__service__pb2.IngestRequest.SerializeToString,
            foreverbull_dot_backtest_dot_engine__service__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foreverbull.backtest.Engine/RunBacktest',
            foreverbull_dot_backtest_dot_engine__service__pb2.RunRequest.SerializeToString,
            foreverbull_dot_backtest_dot_engine__service__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentPeriod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foreverbull.backtest.Engine/GetCurrentPeriod',
            foreverbull_dot_backtest_dot_engine__service__pb2.GetCurrentPeriodRequest.SerializeToString,
            foreverbull_dot_backtest_dot_engine__service__pb2.GetCurrentPeriodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrdersAndContinue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foreverbull.backtest.Engine/PlaceOrdersAndContinue',
            foreverbull_dot_backtest_dot_engine__service__pb2.PlaceOrdersAndContinueRequest.SerializeToString,
            foreverbull_dot_backtest_dot_engine__service__pb2.PlaceOrdersAndContinueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foreverbull.backtest.Engine/GetResult',
            foreverbull_dot_backtest_dot_engine__service__pb2.GetResultRequest.SerializeToString,
            foreverbull_dot_backtest_dot_engine__service__pb2.GetResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/foreverbull.backtest.Engine/Stop',
            foreverbull_dot_backtest_dot_engine__service__pb2.StopRequest.SerializeToString,
            foreverbull_dot_backtest_dot_engine__service__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
