"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .deleteconsumerresponse import (
    DeleteConsumerResponse,
    DeleteConsumerResponseTypedDict,
)
from .unexpectederrorresponse import (
    UnexpectedErrorResponse,
    UnexpectedErrorResponseTypedDict,
)
from apideck_unify.types import BaseModel
from apideck_unify.utils import FieldMetadata, HeaderMetadata, PathParamMetadata
import pydantic
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class VaultConsumersDeleteGlobalsTypedDict(TypedDict):
    app_id: NotRequired[str]
    r"""The ID of your Unify application"""


class VaultConsumersDeleteGlobals(BaseModel):
    app_id: Annotated[
        Optional[str],
        pydantic.Field(alias="x-apideck-app-id"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""The ID of your Unify application"""


class VaultConsumersDeleteRequestTypedDict(TypedDict):
    consumer_id: str
    r"""ID of the consumer to return"""


class VaultConsumersDeleteRequest(BaseModel):
    consumer_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""ID of the consumer to return"""


VaultConsumersDeleteResponseTypedDict = TypeAliasType(
    "VaultConsumersDeleteResponseTypedDict",
    Union[DeleteConsumerResponseTypedDict, UnexpectedErrorResponseTypedDict],
)


VaultConsumersDeleteResponse = TypeAliasType(
    "VaultConsumersDeleteResponse",
    Union[DeleteConsumerResponse, UnexpectedErrorResponse],
)
