__version__ = '0.0.1'
__title__ = 'zwimage'
__description__ = 'Personal Image Utilities'
__url__ = 'https://github.com/njzhaowei/zwimage'
__author__ = 'Zhao Wei'
__author_email__ = 'yewberry@163.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2024 Zhao Wei. All rights reserved.'
