RANGE = 2
ANY = 3
AT_LEAST_ONE = 4
EXACT = 1
COUNT_TYPES = ( EXACT, RANGE, ANY, AT_LEAST_ONE, )
INFINITY = 1000000
ANY_CHAR = "*"
AT_LEAST_ONE_CHAR = "+"
SPECIAL_CHARS = {
    ANY: ANY_CHAR,
    AT_LEAST_ONE: AT_LEAST_ONE_CHAR,
}