class Types:
    PERCENTAGE = 'PERCENTAGE'
    BOOL = 'BOOL'
    MONEY = 'MONEY'
    NUMBER = 'NUMBER'
    INTEGER = 'INTEGER'
    GEO = 'GEO'
    CHAR = 'CHAR'
    URL = 'URL'
    LIST = 'LIST'
    DATE = 'DATE'
    JSON = 'JSON'
    STRING = 'STRING'
    ELEMENT = 'ELEMENT'