"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .serverlesschatcompletebody import (
    ServerlessChatCompleteBody,
    ServerlessChatCompleteBodyTypedDict,
)
from friendli.types import BaseModel
from friendli.utils import FieldMetadata, HeaderMetadata, RequestMetadata
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ServerlessChatCompleteRequestTypedDict(TypedDict):
    serverless_chat_complete_body: ServerlessChatCompleteBodyTypedDict
    x_friendli_team: NotRequired[str]
    r"""ID of team to run requests as (optional parameter)."""


class ServerlessChatCompleteRequest(BaseModel):
    serverless_chat_complete_body: Annotated[
        ServerlessChatCompleteBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    x_friendli_team: Annotated[
        Optional[str],
        pydantic.Field(alias="X-Friendli-Team"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ] = None
    r"""ID of team to run requests as (optional parameter)."""
