"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .streamedtoolassistedchattoken import (
    StreamedToolAssistedChatToken,
    StreamedToolAssistedChatTokenTypedDict,
)
from .streamedtoolassistedchattoolstatus import (
    StreamedToolAssistedChatToolStatus,
    StreamedToolAssistedChatToolStatusTypedDict,
)
from typing import Union
from typing_extensions import TypeAliasType


StreamedToolAssistedChatResultTypedDict = TypeAliasType(
    "StreamedToolAssistedChatResultTypedDict",
    Union[
        StreamedToolAssistedChatTokenTypedDict,
        StreamedToolAssistedChatToolStatusTypedDict,
    ],
)
r"""A server-sent event containing chat completions content."""


StreamedToolAssistedChatResult = TypeAliasType(
    "StreamedToolAssistedChatResult",
    Union[StreamedToolAssistedChatToken, StreamedToolAssistedChatToolStatus],
)
r"""A server-sent event containing chat completions content."""
