channel_info = {
    "ch💬profit_loss💸": "A channel for discussing profit and loss in trading and investing. 💸",
   
    "ch💬offtopic⬅": "An off-topic channel for casual conversations and discussions. ⬅",
   
    "ch💬paper-trading": "A channel for discussing paper trading strategies and experiences.",
   
    "🤖command_room": "A command room for bot-related activities and commands. 🤖",
   
    "🗣announcements":"Channel for important announcements and updates. 📢",
   
    "rss🔊finra":"Channel for receiving FINRA-related RSS feed updates. 🔊",
   
    "rss🔊sec":"Channel for receiving SEC-related RSS feed updates. 🔊",
   
    "fm❓questions": "A channel for asking and answering questions related to financial markets. ❓",
   
    "ch💬hangout": "A casual hangout channel for members to socialize and chat. 🍻",
   
    "rss🔊dtcc": "Channel for receiving DTCC-related RSS feed updates. 🔊",
   
    "rss🔊nscc": "Channel for receiving NSCC-related RSS feed updates. 🔊",
   
    "fd📶opening_flow": "Channel for tracking opening flow and market activities. 📈",
   
    "rss🔊mad_money": "Channel for receiving Mad Money-related RSS feed updates. 🔊",
   
    "cv📜sec-filings": "Discussion and videos related to SEC filings and related topics. 📑",
    "cv📜history": "Discussion and videos related to historical market events and data. 📈📉",
    "cv📜psychology": "Discussion and videos related to trading psychology and mindset. 🧠💡",
    "cv📜trading": "Discussion and videos related to trading strategies and techniques. 📊",
    "cv📜macro": "Discussion and videos related to macroeconomic factors and trends. 🌍💹",
    "cv📜china": "Discussion and videos related to the Chinese market and economy. 🇨🇳",
    "cv📜research": "Sharing and discussion of videos related to research on financial markets. 📊📈",
    "cv📜markets": "Discussion and videos related to various financial markets and assets. 🌐💹",
    "cv📜analysis": "Sharing and discussion of videos related to market analysis. 📈📉",
    "cv📜core": "Discussion and videos related to core concepts in trading and investing. 📚🤓",
    "cv📜debunks": "Discussion and videos debunking market myths and misconceptions. 🔍📉",
    "cv📜papers_works": "Sharing of academic papers and research works related to finance through videos. 📝📊",
    "ta📈technicals": "Channel for discussing technical analysis and chart patterns. 📈📊",
   
    "rss🔊cnbc": "Channel for receiving CNBC-related RSS feed updates. 🔊",
   
    "rss🔊nytimes": "Channel for receiving New York Times-related RSS feed updates. 🔊",
   
    "rss🔊yahoo": "Channel for receiving Yahoo Finance-related RSS feed updates. 🔊",
   
    "rss🔊marketbeat": "Channel for receiving MarketBeat-related RSS feed updates. 🔊",
   
    "⚡specials": "Specialized options feeds that run through a variety of filters. NFA.⚡",
   
    "fd📶buys_sells": "Channel for tracking buys and sells in the market from openBB. 📈📉",
   
    "fd📶unusual": "Channel for tracking unusual market activities and trends from openBB. 🧐",
   
    "fd📶goldensweep": "Channel for tracking golden sweeps and trading opportunities from openBB. ✨",
   
 

    
    "rules": "A channel for discussing and understanding the community rules and guidelines. 📜",
 
    "Learn🐍Python":"A channel for learning and discussing Python programming. 🐍",

    "introduction🐍": "An introduction channel for newcomers to the Python programming discussions. 🐍",
  
    "data🐍structures":  "A channel for discussing data structures and algorithms in Python. 🐍🧮",
    "discord🐍bot": "A channel for discussions related to creating Discord bots with Python. 🤖🐍",

    "code🐍snippets": "A channel for sharing and discussing Python code snippets. 💻🐍",

    "ai🔮news": "A channel for live Tradytic AI news and updates about the markets. 📰🔮",
    "bullseye🔮": "A channel for live Tradytic AI discussions and information about accurate predictions and targets. 🎯🔮",
    "stock🔮breakouts": "A channel for live Tradytic AI tracking of stock breakout opportunities. 🚀🔮",
    "darkpool🔮": "A channel for live Tradytic AI discussions and information about dark pool trading. 🌑🔮",
    "option🔮sweeps": "A channel for live Tradytic AI tracking of option sweep activities in the market. 🌊🔮",
    "golden🔮sweeps": "A channel for live Tradytic AI tracking of golden option sweeps and trading opportunities. ✨🔮",
    "scalps🔮": "A channel for live Tradytic AI discussions and information about scalping strategies. 💫🔮",
    "crypto🔮signals": "A channel for live Tradytic AI signals and information about cryptocurrency trading. 🪙🔮",
    "analyst🔮grades": "A channel for live Tradytic AI tracking of analyst grades and recommendations. 📈🔮",
    "insider🔮trades": "A channel for live Tradytic AI insider trading information",
    "sweeps": "Channel for sweep trades",
    "multiauto🆚single": "Comparison between multi and single auto trades",
    "multi🦜auction": "Multi-auction trading channel",
    "single🦜leg🦜floor": "Channel for single-leg floor trades",
    "single🦜auction": "Single-auction trading channel",
    "Momentum💫Scalps": "Channel for momentum scalping strategies",
    "scalps💫hour⏫": "Scalping opportunities on an hourly basis",
    "scalps💫day⏫": "Scalping opportunities on a daily basis",
    "SECTOR🫧DARK🫧POOLS": "Information related to dark pools in different sectors",
    "COMPANY FILINGS": "Channel for company filing news",
    "STOCK CONDITIONS": "Information on stock conditions",
    "rsi🐂minute🐻": "Relative Strength Index (RSI) analysis on a minute basis",
    "odd🦜lot": "Channel for odd lot trading information",
    "CRYPTO🪙FEEDS": "Crypto-related news and feeds",
    "auto🦜execution": "Automated execution of trades",
    "multi🤖auto🤖elec": "Multiple automated electronic trading strategies",
    "MARKET📰NEWS": "General market news and updates",
    "rsi🐂week🐻": "RSI analysis on a weekly basis",
    "rsi🐂hour🐻": "RSI analysis on an hourly basis",
    "option🦜auction": "Channel for options auctions",
    "iso🦜auction": "Channel for ISO auctions",
    "single🦜cross": "Channel for single-leg crosses",
    "options🦜auction": "Auctions related to options",
    "STOCK FEEDS": "Stock market feeds and information",
    "only🦜canceled": "Information about canceled trades",
    "multi🦜proprietary": "Multiple proprietary trading strategies",
    "zero⭕dte✨": "Zero-day-to-expiration trading strategies",
    "TECHNICAL📈SIGNALS": "Technical trading signals",
    "scalps💫minute⏫": "Scalping opportunities on a minute-to-minute basis",
    "INDICES ZONE": "Information related to stock market indices",
    "GREEKS": "Discussion of Greek letters in options trading",
    "tom": "Information related to TOM trading",
    "accumulation🚀": "Accumulation trading strategies",
    "single🦜iso": "Single ISO trading information",
    "fire🔥sale": "Opportunities for buying during a market downturn",
    "new🔝52high": "Stocks hitting new 52-week highs",
    "new🔝52low": "Stocks hitting new 52-week lows",
    "near🔺52🔺high": "Stocks nearing their 52-week highs",
    "near🔺52🔺low": "Stocks nearing their 52-week lows",
    "short🩸sale🩸rule": "Information on short sale rules",
    "deficient": "Information about deficient stocks",
    "PLAYS": "Stock trading plays",
    "td9⏺minute": "Trading based on TD9 indicators on a minute basis",
    "trady🔮flow": "Trading based on order flow analysis",
    "social🔮spike": "Trading based on social media spikes",
    "crypto🔮breakouts": "Crypto breakouts and trading opportunities",
    "above🔺avg🔺vol": "Stocks with above-average volume",
    "below🔺avg🔺vol": "Stocks with below-average volume",
    "rsi🐂day🐻": "RSI analysis on a daily basis",
    "ch💬mods-batcave": "Chat channel for moderators - Batcave",
    "vc☎main_voice": "Voice chat for main discussions",
    "technology💻": "Live dark pool feed for the technology sector",
    "healthcare🏥": "Live dark pool feed for the healthcare sector",
    "consumer🛍def": "Live dark pool feed for the consumer goods sector",
    "cons🍞staples": "Live dark pool feed for the consumer staples sector",
    "energy⛽": "Live dark pool feed for the energy sector",
    "financials💰": "Live dark pool feed for the financial sector",
    "industrials🏗": "Live dark pool feed for the industrial sector",
    "materials⛏": "Live dark pool feed for the materials sector",
    "real🏠estate": "Live dark pool feed for the real estate sector",
    "utilities💡": "Live dark pool feed for the utilities sector",
    "telecommunications📞": "Telecommunications sector information",
    "superstonk🧧": "Reddit surveillance channel for Superstonk community.",
    "investing🧧": "Reddit surveillance channel for r/investing.",
    "crypto🧧": "Reddit surveillance channel for crypto-related discussions",
    "amcstock🧧": "Reddit surveillance channel for AMC stock discussions",
    "finance🧧": "Reddit surveillance channel for financial discussions",
    "options🧧": "Reddit surveillance channel for options trading discussions",
    "wsb🧧": "WallStreetBets (WSB) discussions",
    "ch💬tinfoil-hat": "Chat channel for tinfoil hat discussions",
    "etfs⚓": "Exchange-traded funds (ETFs) discussions",
    "test🏗": "Test channel for various purposes",
    "98percent➕cost": "Discussion of costs above 98%",
    "2percent➖cost": "Discussion of costs below 2%",
    "scalps💫week⏫": "Scalping opportunities on a weekly basis",
    "prospectus📜": "Information related to prospectuses",
    "quarterly📜report": "Quarterly report-related information",
    "securities📜sale": "Information about securities sales",
    "annual📜report": "Annual report-related information",
    "shelf📜offering": "Information about shelf offerings",
    "current📜report": "Current report-related information",
    "notice📜effectiveness": "Notices related to effectiveness",
    "beneficial📜change": "Changes in beneficial ownership",
    "emp📜offering": "Employee offerings information",
    "foreign📜issuer": "Information about foreign issuers",
    "volume🟰total": "Total trading volume information",
    "ch💬spx-spy-trades": "Chat channel for SPX and SPY trades",
    "options🦜floor": "Options trading on the floor",
    "late🦜": "Live option trades that are executed late",
    "option🦜cross": "Live option trades that involve crosses",
    "out🦜of🦜seq": "Live option trades that are out of sequence",
    "options🦜auto": "Live discussions and conditions of automated option trades",
    "500➖1k➖vol": "Live Stocks trades  with volume between 500 and 1,000",
    "1k➖10k➖vol": "Live Stocks tradeswith volume between 1,000 and 10,000",
    "10k➖50k➖vol": "Live Stocks trades with volume between 10,000 and 50,000",
    "50k➕vol": "Live Stocks trades with volume above 50,000",
    "nport📜etfs": "NPORT ETFs information",
    "security📜register": "Information about security registers",
    "13g📜amended": "Amended 13G filings",
    "13f📜": "13F filings information",
    "late📜filing": "Late filing information",
    "materials📜": "Materials sector filings",
    "td9⏺options": "Options trading based on TD9 indicators",
    "td9⏺5minute": "5-minute trading based on TD9 indicators",
    "td9⏺day": "Daily trading based on TD9 indicators",
    "td9⏺15minute": "15-minute trading based on TD9 indicators",
    "td9⏺30minute": "30-minute trading based on TD9 indicators",
    "td9⏺hour": "Hourly trading based on TD9 indicators",
    "td9⏺2hr": "2-hour trading based on TD9 indicators",
    "td9⏺4hr": "4-hour trading based on TD9 indicators",
    "multifloor🆚single": "Comparison between multi-floor and single-floor trading",
    "cash🏯sale": "Cash sale trading information",
    "intmarket🏯sweep": "International market sweeps",
    "trade🏯exempt": "Exempt market trading information",
    "qual_contingent": "Qualitative contingent trading information",
    "contingent": "Contingent trading information",
    "macd❌minute": "MACD analysis on a minute basis",
    "10k➕buys": "Buys with a volume above 10,000",
    "spx_indices": "Information related to S&P indices",
    "dow_indices": "Information related to Dow indices",
    "nasdaq_indices": "Information related to NASDAQ indices",
    "oi➖5k➖10k": "Live option trades with Open interest between 5,000 and 10,000",
    "oi➖10k➖50k": "Live option trades with Open interest between 10,000 and 50,000",
    "oi➖50k➖100k": "Live option trades with Open interest between 50,000 and 100,000",
    "oi➕100k": "Live option trades with Open interest above 100,000",
    "theta🛡resistant": "Theta-resistant trading strategies",
    "neutral😐zone": "Trading strategies in a neutral market",
    "trade🐍code": "Trading based on trade codes",
    "opening🦜canceled": "Opening trades that were canceled",
    "form🏯t": "Trading based on Form T",
    "post📜effective📜amendment": "Amendments to post-effective forms",
    "fidelity📜bond": "Fidelity bond information",
    "new📜date": "New date-related trading",
    "preliminary📜proxy": "Preliminary proxy-related trading",
    "form📜cert": "Form certification trading",
    "foreign📜registration": "Foreign registration trading",
    "163📜433": "Trading related to 163.433 forms",
    "business📜combos": "Trading related to business combinations",
    "tender📜offer": "Trading related to tender offers",
    "removal📜report": "Removal report trading",
    "initial📜beneficial": "Initial beneficial ownership trading",
    "summary📜prospectus": "Trading based on summary prospectuses",
    "shareholder📜report": "Shareholder report trading",
    "rsi🐂month🐻": "Tickers trading overbought or oversold on the monthly timeframe.",
    "individual📜ownership": "Individual ownership trading",
    "td9⏺week": "Weekly trading based on TD9 indicators",
    "td9⏺month": "Monthly trading based on TD9 indicators",
    "10k➕sells🟥": "Sells with a volume above 10,000",
    "gemi": "Discussion related to Gemi trading",
    "short_leveraged": "Trading of short leveraged assets",
    "russell": "Discussion related to Russell trading",
    "emerging_markets": "Trading in emerging markets",
    "skew": "Discussion related to skew in trading",
    "news🏗": "News-related discussions",
    "quants🏗": "Quantitative trading discussions",
    "press📃release": "News related to press releases",
    "earnings📃ah": "News about earnings announcements after hours",
    "investing📃": "General news and discussions related to investing",
    "product📃announce": "News and announcements about product launches",
    "analysts📃": "News and discussions related to analysts' reports",
    "penny📃stocks": "News and discussions related to penny stocks trading",
    "futures📃forex": "News and discussions related to futures and forex markets",
    "fed📃government": "News and discussions related to the Federal Government",
    "options📃": "News and discussions related to options trading",
    "corp📃actions": "News and discussions related to corporate actions",
    "research📃": "News and discussions related to research",
    "emerging📃markets": "News and discussions related to emerging markets",
    "intraday📃movers": "News and discussions related to intraday market movers",
    "trading📃": "News and discussions related to trading strategies",
    "etfs📃": "News and discussions related to ETFs (Exchange-Traded Funds)",
    "sector📃specific": "News and discussions related to sector-specific developments",
    "regulatory📃legal": "News and discussions related to regulatory and legal matters",
    "calendars📃events": "News and discussions related to calendars and events",
    "top📃general": "General news and top-related discussions",
    "index⚡surge": "Index option trades that have sudden volume.",
    "bankruptcy📃": "Bankruptcy-related discussions",
    "shares📜changed": "Information about shares that changed",
    "dip⚡specials": "Options trading on a DIP - specialized feed.",
    "insider📜trades": "Channel for insider trades information.",
    "mgmt📜changes": "Channel for management changes updates.",
    "experiments": "Channel for discussions and information related to experiments.",
    "repeated_hits": "Channel for stock and option trades that have repeated activity in a short period.",
    "macd❌hour": "Channel for MACD (Moving Average Convergence Divergence) analysis on an hourly basis.",
    "macd❌day": "Channel for MACD (Moving Average Convergence Divergence) analysis on a daily basis.",
    "macd❌week": "Channel for MACD (Moving Average Convergence Divergence) analysis on a weekly basis.",
    "macd❌month": "Channel for MACD (Moving Average Convergence Divergence) analysis on a monthly basis."}



fudstop_logo = "https://media.discordapp.net/attachments/938986871223091231/941151745898344508/FS_Logo_9.gif?ex=65b1c0dd&is=659f4bdd&hm=c6df5ef4bb9c3e1a99a86c95b8084bbff8c4b3ab91d290a7fbabd52ebd6975b3&=&width=539&height=539"