# coding: utf-8

"""
    NinjaAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kitchenai_python_sdk.models.file_object_schema import FileObjectSchema

class TestFileObjectSchema(unittest.TestCase):
    """FileObjectSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileObjectSchema:
        """Test FileObjectSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileObjectSchema`
        """
        model = FileObjectSchema()
        if include_optional:
            return FileObjectSchema(
                name = '',
                ingest_label = '',
                metadata = {
                    'key' : ''
                    }
            )
        else:
            return FileObjectSchema(
                name = '',
        )
        """

    def testFileObjectSchema(self):
        """Test FileObjectSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
