"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import cosmos.base.v1beta1.coin_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Params(google.protobuf.message.Message):
    """Params defines the parameters for the module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADD_SERVICE_FEE_FIELD_NUMBER: builtins.int
    @property
    def add_service_fee(self) -> cosmos.base.v1beta1.coin_pb2.Coin:
        """The amount of uPOKT required to add a new service.
        This will be deducted from the signer's account balance,
        and transferred to the pocket network foundation.
        """

    def __init__(
        self,
        *,
        add_service_fee: cosmos.base.v1beta1.coin_pb2.Coin | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["add_service_fee", b"add_service_fee"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["add_service_fee", b"add_service_fee"]) -> None: ...

global___Params = Params
