# coding: utf-8

"""
    Документация Ozon Seller API

    По вопросам работы с Seller API, обращайтесь в поддержку через личный кабинет.  > [Инструкции по работе с маркетплейсом](https://seller-edu.ozon.ru)  > [Информационная платформа и сообщество разработчиков Ozon for Dev](https://dev.ozon.ru/)   # noqa: E501

    OpenAPI spec version: 2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ItemCommissions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fbo_deliv_to_customer_amount': 'float',
        'fbo_direct_flow_trans_max_amount': 'float',
        'fbo_direct_flow_trans_min_amount': 'float',
        'fbo_fulfillment_amount': 'float',
        'fbo_return_flow_amount': 'float',
        'fbo_return_flow_trans_min_amount': 'float',
        'fbo_return_flow_trans_max_amount': 'float',
        'fbs_deliv_to_customer_amount': 'float',
        'fbs_direct_flow_trans_max_amount': 'float',
        'fbs_direct_flow_trans_min_amount': 'float',
        'fbs_first_mile_min_amount': 'float',
        'fbs_first_mile_max_amount': 'float',
        'fbs_return_flow_amount': 'float',
        'fbs_return_flow_trans_max_amount': 'float',
        'fbs_return_flow_trans_min_amount': 'float',
        'sales_percent_fbo': 'float',
        'sales_percent_fbs': 'float',
        'sales_percent': 'float'
    }

    attribute_map = {
        'fbo_deliv_to_customer_amount': 'fbo_deliv_to_customer_amount',
        'fbo_direct_flow_trans_max_amount': 'fbo_direct_flow_trans_max_amount',
        'fbo_direct_flow_trans_min_amount': 'fbo_direct_flow_trans_min_amount',
        'fbo_fulfillment_amount': 'fbo_fulfillment_amount',
        'fbo_return_flow_amount': 'fbo_return_flow_amount',
        'fbo_return_flow_trans_min_amount': 'fbo_return_flow_trans_min_amount',
        'fbo_return_flow_trans_max_amount': 'fbo_return_flow_trans_max_amount',
        'fbs_deliv_to_customer_amount': 'fbs_deliv_to_customer_amount',
        'fbs_direct_flow_trans_max_amount': 'fbs_direct_flow_trans_max_amount',
        'fbs_direct_flow_trans_min_amount': 'fbs_direct_flow_trans_min_amount',
        'fbs_first_mile_min_amount': 'fbs_first_mile_min_amount',
        'fbs_first_mile_max_amount': 'fbs_first_mile_max_amount',
        'fbs_return_flow_amount': 'fbs_return_flow_amount',
        'fbs_return_flow_trans_max_amount': 'fbs_return_flow_trans_max_amount',
        'fbs_return_flow_trans_min_amount': 'fbs_return_flow_trans_min_amount',
        'sales_percent_fbo': 'sales_percent_fbo',
        'sales_percent_fbs': 'sales_percent_fbs',
        'sales_percent': 'sales_percent'
    }

    def __init__(self, fbo_deliv_to_customer_amount=None, fbo_direct_flow_trans_max_amount=None, fbo_direct_flow_trans_min_amount=None, fbo_fulfillment_amount=None, fbo_return_flow_amount=None, fbo_return_flow_trans_min_amount=None, fbo_return_flow_trans_max_amount=None, fbs_deliv_to_customer_amount=None, fbs_direct_flow_trans_max_amount=None, fbs_direct_flow_trans_min_amount=None, fbs_first_mile_min_amount=None, fbs_first_mile_max_amount=None, fbs_return_flow_amount=None, fbs_return_flow_trans_max_amount=None, fbs_return_flow_trans_min_amount=None, sales_percent_fbo=None, sales_percent_fbs=None, sales_percent=None):  # noqa: E501
        """ItemCommissions - a model defined in Swagger"""  # noqa: E501
        self._fbo_deliv_to_customer_amount = None
        self._fbo_direct_flow_trans_max_amount = None
        self._fbo_direct_flow_trans_min_amount = None
        self._fbo_fulfillment_amount = None
        self._fbo_return_flow_amount = None
        self._fbo_return_flow_trans_min_amount = None
        self._fbo_return_flow_trans_max_amount = None
        self._fbs_deliv_to_customer_amount = None
        self._fbs_direct_flow_trans_max_amount = None
        self._fbs_direct_flow_trans_min_amount = None
        self._fbs_first_mile_min_amount = None
        self._fbs_first_mile_max_amount = None
        self._fbs_return_flow_amount = None
        self._fbs_return_flow_trans_max_amount = None
        self._fbs_return_flow_trans_min_amount = None
        self._sales_percent_fbo = None
        self._sales_percent_fbs = None
        self._sales_percent = None
        self.discriminator = None
        if fbo_deliv_to_customer_amount is not None:
            self.fbo_deliv_to_customer_amount = fbo_deliv_to_customer_amount
        if fbo_direct_flow_trans_max_amount is not None:
            self.fbo_direct_flow_trans_max_amount = fbo_direct_flow_trans_max_amount
        if fbo_direct_flow_trans_min_amount is not None:
            self.fbo_direct_flow_trans_min_amount = fbo_direct_flow_trans_min_amount
        if fbo_fulfillment_amount is not None:
            self.fbo_fulfillment_amount = fbo_fulfillment_amount
        if fbo_return_flow_amount is not None:
            self.fbo_return_flow_amount = fbo_return_flow_amount
        if fbo_return_flow_trans_min_amount is not None:
            self.fbo_return_flow_trans_min_amount = fbo_return_flow_trans_min_amount
        if fbo_return_flow_trans_max_amount is not None:
            self.fbo_return_flow_trans_max_amount = fbo_return_flow_trans_max_amount
        if fbs_deliv_to_customer_amount is not None:
            self.fbs_deliv_to_customer_amount = fbs_deliv_to_customer_amount
        if fbs_direct_flow_trans_max_amount is not None:
            self.fbs_direct_flow_trans_max_amount = fbs_direct_flow_trans_max_amount
        if fbs_direct_flow_trans_min_amount is not None:
            self.fbs_direct_flow_trans_min_amount = fbs_direct_flow_trans_min_amount
        if fbs_first_mile_min_amount is not None:
            self.fbs_first_mile_min_amount = fbs_first_mile_min_amount
        if fbs_first_mile_max_amount is not None:
            self.fbs_first_mile_max_amount = fbs_first_mile_max_amount
        if fbs_return_flow_amount is not None:
            self.fbs_return_flow_amount = fbs_return_flow_amount
        if fbs_return_flow_trans_max_amount is not None:
            self.fbs_return_flow_trans_max_amount = fbs_return_flow_trans_max_amount
        if fbs_return_flow_trans_min_amount is not None:
            self.fbs_return_flow_trans_min_amount = fbs_return_flow_trans_min_amount
        if sales_percent_fbo is not None:
            self.sales_percent_fbo = sales_percent_fbo
        if sales_percent_fbs is not None:
            self.sales_percent_fbs = sales_percent_fbs
        if sales_percent is not None:
            self.sales_percent = sales_percent

    @property
    def fbo_deliv_to_customer_amount(self):
        """Gets the fbo_deliv_to_customer_amount of this ItemCommissions.  # noqa: E501

        Последняя миля (FBO).  # noqa: E501

        :return: The fbo_deliv_to_customer_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbo_deliv_to_customer_amount

    @fbo_deliv_to_customer_amount.setter
    def fbo_deliv_to_customer_amount(self, fbo_deliv_to_customer_amount):
        """Sets the fbo_deliv_to_customer_amount of this ItemCommissions.

        Последняя миля (FBO).  # noqa: E501

        :param fbo_deliv_to_customer_amount: The fbo_deliv_to_customer_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbo_deliv_to_customer_amount = fbo_deliv_to_customer_amount

    @property
    def fbo_direct_flow_trans_max_amount(self):
        """Gets the fbo_direct_flow_trans_max_amount of this ItemCommissions.  # noqa: E501

        Магистраль до (FBO).  # noqa: E501

        :return: The fbo_direct_flow_trans_max_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbo_direct_flow_trans_max_amount

    @fbo_direct_flow_trans_max_amount.setter
    def fbo_direct_flow_trans_max_amount(self, fbo_direct_flow_trans_max_amount):
        """Sets the fbo_direct_flow_trans_max_amount of this ItemCommissions.

        Магистраль до (FBO).  # noqa: E501

        :param fbo_direct_flow_trans_max_amount: The fbo_direct_flow_trans_max_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbo_direct_flow_trans_max_amount = fbo_direct_flow_trans_max_amount

    @property
    def fbo_direct_flow_trans_min_amount(self):
        """Gets the fbo_direct_flow_trans_min_amount of this ItemCommissions.  # noqa: E501

        Магистраль от (FBO).  # noqa: E501

        :return: The fbo_direct_flow_trans_min_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbo_direct_flow_trans_min_amount

    @fbo_direct_flow_trans_min_amount.setter
    def fbo_direct_flow_trans_min_amount(self, fbo_direct_flow_trans_min_amount):
        """Sets the fbo_direct_flow_trans_min_amount of this ItemCommissions.

        Магистраль от (FBO).  # noqa: E501

        :param fbo_direct_flow_trans_min_amount: The fbo_direct_flow_trans_min_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbo_direct_flow_trans_min_amount = fbo_direct_flow_trans_min_amount

    @property
    def fbo_fulfillment_amount(self):
        """Gets the fbo_fulfillment_amount of this ItemCommissions.  # noqa: E501

        Комиссия за сборку заказа (FBO).  # noqa: E501

        :return: The fbo_fulfillment_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbo_fulfillment_amount

    @fbo_fulfillment_amount.setter
    def fbo_fulfillment_amount(self, fbo_fulfillment_amount):
        """Sets the fbo_fulfillment_amount of this ItemCommissions.

        Комиссия за сборку заказа (FBO).  # noqa: E501

        :param fbo_fulfillment_amount: The fbo_fulfillment_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbo_fulfillment_amount = fbo_fulfillment_amount

    @property
    def fbo_return_flow_amount(self):
        """Gets the fbo_return_flow_amount of this ItemCommissions.  # noqa: E501

        Комиссия за возврат и отмену (FBO).  # noqa: E501

        :return: The fbo_return_flow_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbo_return_flow_amount

    @fbo_return_flow_amount.setter
    def fbo_return_flow_amount(self, fbo_return_flow_amount):
        """Sets the fbo_return_flow_amount of this ItemCommissions.

        Комиссия за возврат и отмену (FBO).  # noqa: E501

        :param fbo_return_flow_amount: The fbo_return_flow_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbo_return_flow_amount = fbo_return_flow_amount

    @property
    def fbo_return_flow_trans_min_amount(self):
        """Gets the fbo_return_flow_trans_min_amount of this ItemCommissions.  # noqa: E501

        Комиссия за обратную логистику от (FBO).  # noqa: E501

        :return: The fbo_return_flow_trans_min_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbo_return_flow_trans_min_amount

    @fbo_return_flow_trans_min_amount.setter
    def fbo_return_flow_trans_min_amount(self, fbo_return_flow_trans_min_amount):
        """Sets the fbo_return_flow_trans_min_amount of this ItemCommissions.

        Комиссия за обратную логистику от (FBO).  # noqa: E501

        :param fbo_return_flow_trans_min_amount: The fbo_return_flow_trans_min_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbo_return_flow_trans_min_amount = fbo_return_flow_trans_min_amount

    @property
    def fbo_return_flow_trans_max_amount(self):
        """Gets the fbo_return_flow_trans_max_amount of this ItemCommissions.  # noqa: E501

        Комиссия за обратную логистику до (FBO).  # noqa: E501

        :return: The fbo_return_flow_trans_max_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbo_return_flow_trans_max_amount

    @fbo_return_flow_trans_max_amount.setter
    def fbo_return_flow_trans_max_amount(self, fbo_return_flow_trans_max_amount):
        """Sets the fbo_return_flow_trans_max_amount of this ItemCommissions.

        Комиссия за обратную логистику до (FBO).  # noqa: E501

        :param fbo_return_flow_trans_max_amount: The fbo_return_flow_trans_max_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbo_return_flow_trans_max_amount = fbo_return_flow_trans_max_amount

    @property
    def fbs_deliv_to_customer_amount(self):
        """Gets the fbs_deliv_to_customer_amount of this ItemCommissions.  # noqa: E501

        Последняя миля (FBS).  # noqa: E501

        :return: The fbs_deliv_to_customer_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbs_deliv_to_customer_amount

    @fbs_deliv_to_customer_amount.setter
    def fbs_deliv_to_customer_amount(self, fbs_deliv_to_customer_amount):
        """Sets the fbs_deliv_to_customer_amount of this ItemCommissions.

        Последняя миля (FBS).  # noqa: E501

        :param fbs_deliv_to_customer_amount: The fbs_deliv_to_customer_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbs_deliv_to_customer_amount = fbs_deliv_to_customer_amount

    @property
    def fbs_direct_flow_trans_max_amount(self):
        """Gets the fbs_direct_flow_trans_max_amount of this ItemCommissions.  # noqa: E501

        Магистраль до (FBS).  # noqa: E501

        :return: The fbs_direct_flow_trans_max_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbs_direct_flow_trans_max_amount

    @fbs_direct_flow_trans_max_amount.setter
    def fbs_direct_flow_trans_max_amount(self, fbs_direct_flow_trans_max_amount):
        """Sets the fbs_direct_flow_trans_max_amount of this ItemCommissions.

        Магистраль до (FBS).  # noqa: E501

        :param fbs_direct_flow_trans_max_amount: The fbs_direct_flow_trans_max_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbs_direct_flow_trans_max_amount = fbs_direct_flow_trans_max_amount

    @property
    def fbs_direct_flow_trans_min_amount(self):
        """Gets the fbs_direct_flow_trans_min_amount of this ItemCommissions.  # noqa: E501

        Магистраль от (FBS).  # noqa: E501

        :return: The fbs_direct_flow_trans_min_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbs_direct_flow_trans_min_amount

    @fbs_direct_flow_trans_min_amount.setter
    def fbs_direct_flow_trans_min_amount(self, fbs_direct_flow_trans_min_amount):
        """Sets the fbs_direct_flow_trans_min_amount of this ItemCommissions.

        Магистраль от (FBS).  # noqa: E501

        :param fbs_direct_flow_trans_min_amount: The fbs_direct_flow_trans_min_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbs_direct_flow_trans_min_amount = fbs_direct_flow_trans_min_amount

    @property
    def fbs_first_mile_min_amount(self):
        """Gets the fbs_first_mile_min_amount of this ItemCommissions.  # noqa: E501

        Минимальная комиссия за обработку отправления (FBS) — 0 рублей.  [Подробнее о тарифах в Базе знаний продавца](https://seller-edu.ozon.ru/commissions-tariffs/commissions-tariffs-ozon/rashody-na-dop-uslugi#выезд-транспортного-средства-по-адресу-продавца-для-забора-отправлении-(pick-up))   # noqa: E501

        :return: The fbs_first_mile_min_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbs_first_mile_min_amount

    @fbs_first_mile_min_amount.setter
    def fbs_first_mile_min_amount(self, fbs_first_mile_min_amount):
        """Sets the fbs_first_mile_min_amount of this ItemCommissions.

        Минимальная комиссия за обработку отправления (FBS) — 0 рублей.  [Подробнее о тарифах в Базе знаний продавца](https://seller-edu.ozon.ru/commissions-tariffs/commissions-tariffs-ozon/rashody-na-dop-uslugi#выезд-транспортного-средства-по-адресу-продавца-для-забора-отправлении-(pick-up))   # noqa: E501

        :param fbs_first_mile_min_amount: The fbs_first_mile_min_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbs_first_mile_min_amount = fbs_first_mile_min_amount

    @property
    def fbs_first_mile_max_amount(self):
        """Gets the fbs_first_mile_max_amount of this ItemCommissions.  # noqa: E501

        Максимальная комиссия за обработку отправления (FBS) — 25 рублей.  [Подробнее о тарифах в Базе знаний продавца](https://seller-edu.ozon.ru/commissions-tariffs/commissions-tariffs-ozon/rashody-na-dop-uslugi#выезд-транспортного-средства-по-адресу-продавца-для-забора-отправлении-(pick-up))   # noqa: E501

        :return: The fbs_first_mile_max_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbs_first_mile_max_amount

    @fbs_first_mile_max_amount.setter
    def fbs_first_mile_max_amount(self, fbs_first_mile_max_amount):
        """Sets the fbs_first_mile_max_amount of this ItemCommissions.

        Максимальная комиссия за обработку отправления (FBS) — 25 рублей.  [Подробнее о тарифах в Базе знаний продавца](https://seller-edu.ozon.ru/commissions-tariffs/commissions-tariffs-ozon/rashody-na-dop-uslugi#выезд-транспортного-средства-по-адресу-продавца-для-забора-отправлении-(pick-up))   # noqa: E501

        :param fbs_first_mile_max_amount: The fbs_first_mile_max_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbs_first_mile_max_amount = fbs_first_mile_max_amount

    @property
    def fbs_return_flow_amount(self):
        """Gets the fbs_return_flow_amount of this ItemCommissions.  # noqa: E501

        Комиссия за возврат и отмену, обработка отправления (FBS).  # noqa: E501

        :return: The fbs_return_flow_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbs_return_flow_amount

    @fbs_return_flow_amount.setter
    def fbs_return_flow_amount(self, fbs_return_flow_amount):
        """Sets the fbs_return_flow_amount of this ItemCommissions.

        Комиссия за возврат и отмену, обработка отправления (FBS).  # noqa: E501

        :param fbs_return_flow_amount: The fbs_return_flow_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbs_return_flow_amount = fbs_return_flow_amount

    @property
    def fbs_return_flow_trans_max_amount(self):
        """Gets the fbs_return_flow_trans_max_amount of this ItemCommissions.  # noqa: E501

        Комиссия за возврат и отмену, магистраль до (FBS).  # noqa: E501

        :return: The fbs_return_flow_trans_max_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbs_return_flow_trans_max_amount

    @fbs_return_flow_trans_max_amount.setter
    def fbs_return_flow_trans_max_amount(self, fbs_return_flow_trans_max_amount):
        """Sets the fbs_return_flow_trans_max_amount of this ItemCommissions.

        Комиссия за возврат и отмену, магистраль до (FBS).  # noqa: E501

        :param fbs_return_flow_trans_max_amount: The fbs_return_flow_trans_max_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbs_return_flow_trans_max_amount = fbs_return_flow_trans_max_amount

    @property
    def fbs_return_flow_trans_min_amount(self):
        """Gets the fbs_return_flow_trans_min_amount of this ItemCommissions.  # noqa: E501

        Комиссия за возврат и отмену, магистраль от (FBS).  # noqa: E501

        :return: The fbs_return_flow_trans_min_amount of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._fbs_return_flow_trans_min_amount

    @fbs_return_flow_trans_min_amount.setter
    def fbs_return_flow_trans_min_amount(self, fbs_return_flow_trans_min_amount):
        """Sets the fbs_return_flow_trans_min_amount of this ItemCommissions.

        Комиссия за возврат и отмену, магистраль от (FBS).  # noqa: E501

        :param fbs_return_flow_trans_min_amount: The fbs_return_flow_trans_min_amount of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._fbs_return_flow_trans_min_amount = fbs_return_flow_trans_min_amount

    @property
    def sales_percent_fbo(self):
        """Gets the sales_percent_fbo of this ItemCommissions.  # noqa: E501

        Процент комиссии за продажу (FBO).  # noqa: E501

        :return: The sales_percent_fbo of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._sales_percent_fbo

    @sales_percent_fbo.setter
    def sales_percent_fbo(self, sales_percent_fbo):
        """Sets the sales_percent_fbo of this ItemCommissions.

        Процент комиссии за продажу (FBO).  # noqa: E501

        :param sales_percent_fbo: The sales_percent_fbo of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._sales_percent_fbo = sales_percent_fbo

    @property
    def sales_percent_fbs(self):
        """Gets the sales_percent_fbs of this ItemCommissions.  # noqa: E501

        Процент комиссии за продажу (FBS).  # noqa: E501

        :return: The sales_percent_fbs of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._sales_percent_fbs

    @sales_percent_fbs.setter
    def sales_percent_fbs(self, sales_percent_fbs):
        """Sets the sales_percent_fbs of this ItemCommissions.

        Процент комиссии за продажу (FBS).  # noqa: E501

        :param sales_percent_fbs: The sales_percent_fbs of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._sales_percent_fbs = sales_percent_fbs

    @property
    def sales_percent(self):
        """Gets the sales_percent of this ItemCommissions.  # noqa: E501

        Наибольший процент комиссии за продажу среди FBO и FBS.  # noqa: E501

        :return: The sales_percent of this ItemCommissions.  # noqa: E501
        :rtype: float
        """
        return self._sales_percent

    @sales_percent.setter
    def sales_percent(self, sales_percent):
        """Sets the sales_percent of this ItemCommissions.

        Наибольший процент комиссии за продажу среди FBO и FBS.  # noqa: E501

        :param sales_percent: The sales_percent of this ItemCommissions.  # noqa: E501
        :type: float
        """

        self._sales_percent = sales_percent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ItemCommissions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ItemCommissions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
