# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: poktroll/application/types.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'poktroll/application/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from poktroll_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from poktroll_clients.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from poktroll_clients.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from poktroll_clients.proto.poktroll.shared import service_pb2 as poktroll_dot_shared_dot_service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n poktroll/application/types.proto\x12\x14poktroll.application\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x1dpoktroll/shared/service.proto\"\xae\x05\n\x0b\x41pplication\x12\x32\n\x07\x61\x64\x64ress\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x07\x61\x64\x64ress\x12/\n\x05stake\x18\x02 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinR\x05stake\x12R\n\x0fservice_configs\x18\x03 \x03(\x0b\x32).poktroll.shared.ApplicationServiceConfigR\x0eserviceConfigs\x12\\\n\x1b\x64\x65legatee_gateway_addresses\x18\x04 \x03(\tB\x1c\xc8\xde\x1f\x00\xd2\xb4-\x14\x63osmos.AddressStringR\x19\x64\x65legateeGatewayAddresses\x12v\n\x15pending_undelegations\x18\x05 \x03(\x0b\x32;.poktroll.application.Application.PendingUndelegationsEntryB\x04\xc8\xde\x1f\x00R\x14pendingUndelegations\x12;\n\x1aunstake_session_end_height\x18\x06 \x01(\x04R\x17unstakeSessionEndHeight\x12[\n\x10pending_transfer\x18\x07 \x01(\x0b\x32\x30.poktroll.application.PendingApplicationTransferR\x0fpendingTransfer\x1av\n\x19PendingUndelegationsEntry\x12\x10\n\x03key\x18\x01 \x01(\x04R\x03key\x12\x43\n\x05value\x18\x02 \x01(\x0b\x32-.poktroll.application.UndelegatingGatewayListR\x05value:\x02\x38\x01\"d\n\x17UndelegatingGatewayList\x12I\n\x11gateway_addresses\x18\x02 \x03(\tB\x1c\xc8\xde\x1f\x00\xd2\xb4-\x14\x63osmos.AddressStringR\x10gatewayAddresses\"\x95\x01\n\x1aPendingApplicationTransfer\x12I\n\x13\x64\x65stination_address\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x12\x64\x65stinationAddress\x12,\n\x12session_end_height\x18\x02 \x01(\x04R\x10sessionEndHeightB:Z4github.com/pokt-network/poktroll/x/application/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'poktroll.application.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/pokt-network/poktroll/x/application/types\330\342\036\001'
  _globals['_APPLICATION_PENDINGUNDELEGATIONSENTRY']._loaded_options = None
  _globals['_APPLICATION_PENDINGUNDELEGATIONSENTRY']._serialized_options = b'8\001'
  _globals['_APPLICATION'].fields_by_name['address']._loaded_options = None
  _globals['_APPLICATION'].fields_by_name['address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_APPLICATION'].fields_by_name['delegatee_gateway_addresses']._loaded_options = None
  _globals['_APPLICATION'].fields_by_name['delegatee_gateway_addresses']._serialized_options = b'\310\336\037\000\322\264-\024cosmos.AddressString'
  _globals['_APPLICATION'].fields_by_name['pending_undelegations']._loaded_options = None
  _globals['_APPLICATION'].fields_by_name['pending_undelegations']._serialized_options = b'\310\336\037\000'
  _globals['_UNDELEGATINGGATEWAYLIST'].fields_by_name['gateway_addresses']._loaded_options = None
  _globals['_UNDELEGATINGGATEWAYLIST'].fields_by_name['gateway_addresses']._serialized_options = b'\310\336\037\000\322\264-\024cosmos.AddressString'
  _globals['_PENDINGAPPLICATIONTRANSFER'].fields_by_name['destination_address']._loaded_options = None
  _globals['_PENDINGAPPLICATIONTRANSFER'].fields_by_name['destination_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_APPLICATION']._serialized_start=171
  _globals['_APPLICATION']._serialized_end=857
  _globals['_APPLICATION_PENDINGUNDELEGATIONSENTRY']._serialized_start=739
  _globals['_APPLICATION_PENDINGUNDELEGATIONSENTRY']._serialized_end=857
  _globals['_UNDELEGATINGGATEWAYLIST']._serialized_start=859
  _globals['_UNDELEGATINGGATEWAYLIST']._serialized_end=959
  _globals['_PENDINGAPPLICATIONTRANSFER']._serialized_start=962
  _globals['_PENDINGAPPLICATIONTRANSFER']._serialized_end=1111
# @@protoc_insertion_point(module_scope)
