
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/python/calculator_lib:mydist_with_pants

from setuptools import setup

setup(**{
    'author': 'ksajere',
    'classifiers': [
        'Programming Language :: Python :: 3.7',
    ],
    'description': 'An example distribution built with Pants.',
    'install_requires': (
    ),
    'name': 'testing_pants_distribution',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
    ),
    'python_requires': '<=3.12,>=3.10',
    'version': '0.21.0',
})
