__title__ = "lscmf"
__description__ = "Large-scale Collective Matrix Factorization"
__version__ = "0.2.1-1"
__author__ = "Felix Held"
__author_email__ = "felix.held@gmail.com"
__license__ = "bsd-3-clause"
__copyright__ = "Copyright 2020-2024 Felix Held"